=== reixacu/validador-dtd/ASIX.dtd
<!ELEMENT ASIX (alumnes, especialitats, professors, assignatures)>
<!ELEMENT alumnes (alumne+)>
<!ELEMENT alumne (nom, uf+, final)>
<!ATTLIST alumne
      	dni CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT especialitats (especialitat, especialtiat)>
<!ELEMENT especialitat (#PCDATA)>
<!ATTLIST especialitat
      	IDEspecialitat CDATA #IMPLIED
      	IDEspecialtiat CDATA #IMPLIED>
<!ELEMENT especialtiat (#PCDATA)>
<!ATTLIST especialtiat
      	IDEspecialitat CDATA #REQUIRED>
<!ELEMENT professors (professor+)>
<!ELEMENT professor (nom?, especialitat?)>
<!ATTLIST professor
      	IDProfessor CDATA #REQUIRED>
<!ELEMENT assignatures (assignatura+)>
<!ELEMENT assignatura (nom, professor, qualificacions)>
<!ELEMENT qualificacions (alumne+)>
<!ELEMENT uf (#PCDATA)>
<!ATTLIST uf
      	num CDATA #REQUIRED>
<!ELEMENT final (#PCDATA)>

=== reixacu/validador-dtd/ASIX.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ASIX SYSTEM "ASIX.dtd">
<ASIX>

  <!-- ***** ALUMNES ***** -->
  <alumnes>
    <!-- PLANTILLA ALUMNE -->
    <alumne dni="">
      <nom></nom>
    </alumne>

  </alumnes>
  
  <!-- ***** ESPECIALITATS ***** -->
  <especialitats>
    <especialitat IDEspecialtiat="507">Informàtica</especialitat>
    <especialtiat IDEspecialitat="627">Sistemes i aplicacions informàtiques</especialtiat>
  </especialitats>
  
  <!-- ***** PROFESSORS ***** -->
  <professors>
    <professor IDProfessor="P1">
      <nom>Lleonard Carbassa Pons</nom>
      <especialitat IDEspecialitat="507"/>
    </professor>
    <professor IDProfessor="P2">
      <nom>Don Rigoberto Fernández Lopez</nom>
      <especialitat IDEspecialtiat="627"/>
    </professor>
    <professor IDProfessor="P3">
      <nom>Facundo Barberà i Galé</nom>
      <especialitat IDEspecialtiat="507"/>
    </professor>
  </professors>
  
  <!-- ***** ASSIGNATURES I QUALIFICACIONS -->
  <assignatures>
    <assignatura>
      <nom>Llenguatge de marques i sistemes gestors d'informació</nom>
      <professor IDProfessor="P1"/>
      <qualificacions>
        <!-- PLANTILLA QUALIFICACIO ALUMNE -->
        <alumne dni="">
          <uf num="1"></uf>
          <uf num="2"></uf>
          <uf num="3"></uf>
          <final></final>
        </alumne>
        
      </qualificacions>
    </assignatura>
    <assignatura>
      <nom>Administració de Sistemes operatius</nom>
      <professor IDProfessor="P2"/>
      <qualificacions>
        <!-- PLANTILLA QUALIFICACIO ALUMNE -->
        <alumne dni="">
          <uf num="1"></uf>
          <uf num="2"></uf>
          <final></final>
        </alumne>
        
      </qualificacions>
    </assignatura>
    <assignatura>
      <nom>Seguretat i alta disponibilitat</nom>
      <professor IDProfessor="P3"/>
      <qualificacions>
        <!-- PLANTILLA QUALIFICACIO ALUMNE -->
        <alumne dni="">
          <uf num="1"></uf>
          <uf num="2"></uf>
          <uf num="3"></uf>
          <uf num="5"></uf>
          <final></final>
        </alumne>
        
      </qualificacions>
    </assignatura>
  </assignatures>
</ASIX>
